name: Update Service JSON
on:
  push:
    branches:
      - main
jobs:
  update-service-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - run: npm install
        working-directory: ./src/crawler
      - run: node index.mjs
        working-directory: ./src/crawler  
